spring:
  application:
    name: bitbattle-carsearch
logging.level: INFO
server.port: 2517

#jdbc config
jdbc.driverClassName: com.mysql.jdbc.Driver
jdbc.url: jdbc:mysql://mysql_host:3306/RawVehicleInventory
jdbc.username: root
jdbc.password: root
